// ignore_for_file: prefer_const_constructors

import 'dart:developer';

import 'package:flutter/material.dart';
import 'package:geolanesproject/utilies/mycolors.dart';
import 'package:geolanesproject/widgets/custom_button.dart';
import 'package:geolanesproject/widgets/custom_text.dart';

class PurchaseScreen extends StatefulWidget {
  const PurchaseScreen({super.key});

  @override
  State<PurchaseScreen> createState() => _PurchaseScreenState();
}

bool isActive = true;

class _PurchaseScreenState extends State<PurchaseScreen> {
  @override
  Widget build(BuildContext context) {
    double width = MediaQuery.of(context).size.width;
    double height = MediaQuery.of(context).size.height;
    return Scaffold(
      backgroundColor: Mycolor().backgroundcolor,
      body: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          SizedBox(
            height: height * 0.01,
          ),
          CustomText(
            text: "Purchase History",
            fontSize: height * 0.0245,
            fontWeight: FontWeight.w600,
            textcolor: Mycolor().titlecolor,
          ),
          SizedBox(
            height: height * 0.005,
          ),
          CustomText(
            text: "Total revenue generated by the enterprise",
            fontSize: height * 0.014,
            fontWeight: FontWeight.w400,
            textcolor: Mycolor().subtitlecolor,
          ),
          SizedBox(
            height: height * 0.02,
          ),

          //main container..............................
          CustomButton(
            height: height * 0.45,
            width: width,
            padding: EdgeInsets.only(top: height * 0.02),
            decoration: BoxDecoration(
                color: Mycolor().tabbarcolor,
                borderRadius: BorderRadius.only(
                    topLeft: Radius.circular(height * 0.015),
                    topRight: Radius.circular(height * 0.015))),
            child: Column(
              children: [
                //buttons row.........
                Row(
                  mainAxisAlignment: MainAxisAlignment.end,
                  children: [
                    CustomButton(
                      padding: EdgeInsets.symmetric(
                          horizontal: width * 0.02, vertical: height * 0.009),
                      decoration: BoxDecoration(
                          //   border: Border.all(
                          //       width: width * 0.003,
                          //       color: Mycolor().exportbordercolor),
                          color: Mycolor().exportmidcolor,
                          borderRadius: BorderRadius.circular(height * 0.01)),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                        children: [
                          Image.asset(
                            "assets/icons/download.png",
                            height: height * 0.02,
                            color: Mycolor().exporticoncolor,
                          ),
                          SizedBox(
                            width: width * 0.01,
                          ),
                          CustomText(
                            fontWeight: FontWeight.w600,
                            text: "Export",
                            fontSize: height * 0.015,
                            textcolor: Mycolor().exporticoncolor,
                          ),
                        ],
                      ),
                      onTap: () {
                        log("Hello bro");
                      },
                    ),

                    //2nd button.........
                    CustomButton(
                      padding: EdgeInsets.symmetric(
                          horizontal: width * 0.016, vertical: height * 0.007),
                      margin: EdgeInsets.symmetric(horizontal: width * 0.04),
                      decoration: BoxDecoration(
                          border: Border.all(
                              width: width * 0.003,
                              color: Mycolor().fieldbordercolor),
                          borderRadius: BorderRadius.circular(height * 0.01)),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                        children: [
                          Image.asset(
                            "assets/icons/clander.png",
                            height: height * 0.02,
                            color: Mycolor().datecolor,
                          ),
                          SizedBox(
                            width: width * 0.01,
                          ),
                          CustomText(
                            fontWeight: FontWeight.w600,
                            text: "Date",
                            fontSize: height * 0.015,
                            textcolor: Mycolor().datecolor,
                          ),
                        ],
                      ),
                      onTap: () {
                        log("Hello bro");
                      },
                    ),
                    // SizedBox(
                    //   width: width * 0.02,
                    // ),
                    //third button............
                    CustomButton(
                      margin: EdgeInsets.only(right: width * 0.04),
                      padding: EdgeInsets.symmetric(
                          horizontal: width * 0.014, vertical: height * 0.007),
                      decoration: BoxDecoration(
                          border: Border.all(
                              width: width * 0.003,
                              color: Mycolor().fieldbordercolor),
                          borderRadius: BorderRadius.circular(height * 0.01)),
                      child: Row(
                        mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                        children: [
                          Image.asset(
                            "assets/icons/filtericon.png",
                            height: height * 0.02,
                            color: Mycolor().datecolor,
                          ),
                          SizedBox(
                            width: width * 0.01,
                          ),
                          CustomText(
                            fontWeight: FontWeight.w600,
                            text: "Filters",
                            fontSize: height * 0.015,
                            textcolor: Mycolor().datecolor,
                          ),
                        ],
                      ),
                      onTap: () {
                        log("Hello bro");
                      },
                    ),
                  ],
                ),

                //detail container..............

                CustomButton(
                  height: height * 0.04,
                  width: width,
                  margin: EdgeInsets.only(top: height * 0.01),
                  padding: EdgeInsets.symmetric(horizontal: width * 0.03),
                  decoration: BoxDecoration(color: Mycolor().customercolor),
                  child: Row(
                    mainAxisAlignment: MainAxisAlignment.center,
                    crossAxisAlignment: CrossAxisAlignment.center,
                    children: [
                      CustomText(
                        text: "Customer",
                        fontSize: height * 0.014,
                        textcolor: Mycolor().titlecolor,
                        fontWeight: FontWeight.w600,
                      ),
                      Spacer(),
                      CustomText(
                        text: "Start-End Date",
                        fontSize: height * 0.014,
                        textcolor: Mycolor().titlecolor,
                        fontWeight: FontWeight.w600,
                      ),
                      //   SizedBox(
                      //     width: width * 0.04,
                      //   ),
                      Padding(
                        padding: EdgeInsets.symmetric(horizontal: width * 0.06),
                        child: CustomText(
                          text: "Price",
                          fontSize: height * 0.014,
                          textcolor: Mycolor().titlecolor,
                          fontWeight: FontWeight.w600,
                        ),
                      ),
                      CustomText(
                        text: "Status",
                        fontSize: height * 0.014,
                        textcolor: Mycolor().titlecolor,
                        fontWeight: FontWeight.w600,
                      ),
                      Icon(
                        Icons.arrow_drop_down_rounded,
                        color: Mycolor().customerdropiconcolor,
                      )
                    ],
                  ),
                ),

                //listview builder............................
                Expanded(
                  child: ListView.builder(
                    itemCount: 50,
                    itemBuilder: (context, index) {
                      return CustomButton(
                        height: height * 0.05,
                        width: width,
                        margin: EdgeInsets.only(top: height * 0.01),
                        padding: EdgeInsets.symmetric(horizontal: width * 0.03),
                        decoration: BoxDecoration(color: Mycolor().tabbarcolor),
                        child: Row(
                          mainAxisAlignment: MainAxisAlignment.spaceBetween,
                          crossAxisAlignment: CrossAxisAlignment.center,
                          children: [
                            Column(
                              crossAxisAlignment: CrossAxisAlignment.start,
                              children: [
                                CustomText(
                                  text: "Global Travelers",
                                  fontSize: height * 0.014,
                                  textcolor: Mycolor().titlecolor,
                                  fontWeight: FontWeight.w600,
                                ),
                                CustomText(
                                  text: "info@globaltravelers.com",
                                  fontSize: height * 0.011,
                                  textcolor: Mycolor().subtitlecolor,
                                  fontWeight: FontWeight.w400,
                                ),
                              ],
                            ),
                            CustomText(
                              text: "23 -28 Aug 2024",
                              fontSize: height * 0.012,
                              textcolor: Mycolor().titlecolor,
                              fontWeight: FontWeight.w400,
                            ),
                            CustomText(
                              text: "\$120.00",
                              fontSize: height * 0.012,
                              textcolor: Mycolor().titlecolor,
                              fontWeight: FontWeight.w400,
                            ),
                            CustomButton(
                              padding: EdgeInsets.symmetric(
                                  horizontal: height * 0.016,
                                  vertical: height * 0.001),
                              decoration: BoxDecoration(
                                  color: isActive
                                      ? Mycolor().activebutton
                                      : Mycolor().inactive,
                                  borderRadius: BorderRadius.circular(8)),
                              child: CustomText(
                                fontWeight: FontWeight.w600,
                                text: isActive ? "Active" : "Inactive",
                                fontSize: height * 0.014,
                                textcolor: isActive
                                    ? Mycolor().upiconcolor
                                    : Mycolor().badgecolor,
                              ),
                              onTap: () {
                                setState(() {
                                  isActive = !isActive;
                                });
                              },
                            ),
                          ],
                        ),
                      );
                    },
                  ),
                ),
              ],
            ),
          )
        ],
      ),
    );
  }
}
